# Generated by Django 5.0.1 on 2024-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="show_time",
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "performance"),
                name="unique_ticket_seat_performance",
            ),
        ),
    ]
