# Generated by Django 5.0.1 on 2024-01-25 13:39

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_alter_reservation_options_alter_theatrehall_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=service.models.play_img_file_path
            ),
        ),
    ]
