# Generated by Django 4.2 on 2024-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_alter_play_actors_alter_play_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="service.actor"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="genres", to="service.genre"
            ),
        ),
    ]
